import { Component, OnInit } from '@angular/core';

interface completedRaceEvent {
  startDate: string;
  endDate: string;
  month: string;
  raceVenue: string;
  venueDesc: string;
  venueFlag: string;
  firstPosImg: string;
  secondPosImg: string;
  thirdPosImg: string;
  firstPosDriverName: string;
  secondPosDriverName: string;
  thirdPosDriverName: string;
  raceDone: boolean;
  trackImg: string;

}


@Component({
  selector: 'app-homepage',
  templateUrl: './homepage.component.html',
  styleUrls: ['./homepage.component.scss']
})
export class HomepageComponent implements OnInit {


  completedArrEvents: completedRaceEvent[] = [
    { startDate: '26', endDate: '28', month: 'MAR', raceVenue: 'Bahrain', venueDesc: 'Formula 1 Gulf Air Bahrain Grand Prix 2021', venueFlag: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/bahrain-flag.png.transform/2col/image.png', firstPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/lewham01.png.transform/2col/image.png', secondPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/maxver01.png.transform/2col/image.png', thirdPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/valbot01.png.transform/2col/image.png', firstPosDriverName: 'HAM', secondPosDriverName: 'VER', thirdPosDriverName: 'BOT', raceDone: true, trackImg: '' },
    { startDate: '16', endDate: '18', month: 'APR', raceVenue: 'Italy', venueDesc: `Formula 1 Pirelli Gran Premio Del Made In Italy E Dell'emilia Romagna 2021`, venueFlag: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/italy-flag.png.transform/2col/image.png', firstPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/maxver01.png.transform/2col/image.png', secondPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/lewham01.png.transform/2col/image.png', thirdPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/lannor01.png.transform/2col/image.png', firstPosDriverName: 'VER', secondPosDriverName: 'HAM', thirdPosDriverName: 'NOR', raceDone: true, trackImg: '' },
    { startDate: '30', endDate: '02', month: 'APR-MAY', raceVenue: 'Portugal', venueDesc: 'Formula 1 Heineken Grande Prémio De Portugal 2021', venueFlag: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/portugal-flag.png.transform/2col/image.png', firstPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/lewham01.png.transform/2col/image.png', secondPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/maxver01.png.transform/2col/image.png', thirdPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/valbot01.png.transform/2col/image.png', firstPosDriverName: 'HAM', secondPosDriverName: 'VER', thirdPosDriverName: 'BOT', raceDone: true, trackImg: '' },
    { startDate: '07', endDate: '09', month: 'MAY', raceVenue: 'Spain', venueDesc: 'Formula 1 Aramco Gran Premio De España 2021', venueFlag: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/spain-flag.png.transform/2col/image.png', firstPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/lewham01.png.transform/2col/image.png', secondPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/maxver01.png.transform/2col/image.png', thirdPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/valbot01.png.transform/2col/image.png', firstPosDriverName: 'HAM', secondPosDriverName: 'VER', thirdPosDriverName: 'BOT', raceDone: true, trackImg: '' },
    { startDate: '20', endDate: '23', month: 'MAY', raceVenue: 'Monaco', venueDesc: 'Formula 1 Grand Prix De Monaco 2021', venueFlag: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/monaco-flag.png.transform/2col/image.png', firstPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/maxver01.png.transform/2col/image.png', secondPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/carsai01.png.transform/2col/image.png', thirdPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/lannor01.png.transform/2col/image.png', firstPosDriverName: 'VER', secondPosDriverName: 'SAI', thirdPosDriverName: 'NOR', raceDone: true, trackImg: '' },
    { startDate: '04', endDate: '06', month: 'JUN', raceVenue: 'Azerbaijan', venueDesc: 'Formula 1 Azerbaijan Grand Prix 2021', venueFlag: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/azerbaijan-flag.png.transform/2col/image.png', firstPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/serper01.png.transform/2col/image.png', secondPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/sebvet01.png.transform/2col/image.png', thirdPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/piegas01.png.transform/2col/image.png', firstPosDriverName: 'PER', secondPosDriverName: 'VET', thirdPosDriverName: 'GAS', raceDone: true, trackImg: '' },
    { startDate: '18', endDate: '20', month: 'JUN', raceVenue: 'France', venueDesc: 'Formula 1 Emirates Grand Prix De France', venueFlag: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/france-flag.png.transform/2col/image.png', firstPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/maxver01.png.transform/2col/image.png', secondPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/lewham01.png.transform/2col/image.png', thirdPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/serper01.png.transform/2col/image.png', firstPosDriverName: 'VER', secondPosDriverName: 'HAM', thirdPosDriverName: 'PER', raceDone: true, trackImg: '' },
    { startDate: '02', endDate: '04', month: 'JUL', raceVenue: 'Austria', venueDesc: 'Formula 1 BWT Grosser Preis Von Österreich 2021', venueFlag: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/austria-flag.png.transform/2col/image.png', firstPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/maxver01.png.transform/2col/image.png', secondPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/lewham01.png.transform/2col/image.png', thirdPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/serper01.png.transform/2col/image.png', firstPosDriverName: 'VER', secondPosDriverName: 'HAM', thirdPosDriverName: 'PER', raceDone: false, trackImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Great%20Britain%20carbon.png.transform/2col/image.png' },
    { startDate: '02', endDate: '04', month: 'JUL', raceVenue: 'Austria', venueDesc: 'Formula 1 BWT Grosser Preis Von Österreich 2021', venueFlag: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/austria-flag.png.transform/2col/image.png', firstPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/maxver01.png.transform/2col/image.png', secondPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/lewham01.png.transform/2col/image.png', thirdPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/serper01.png.transform/2col/image.png', firstPosDriverName: 'VER', secondPosDriverName: 'HAM', thirdPosDriverName: 'PER', raceDone: false, trackImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Great%20Britain%20carbon.png.transform/2col/image.png' },
    { startDate: '02', endDate: '04', month: 'JUL', raceVenue: 'Austria', venueDesc: 'Formula 1 BWT Grosser Preis Von Österreich 2021', venueFlag: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/austria-flag.png.transform/2col/image.png', firstPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/maxver01.png.transform/2col/image.png', secondPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/lewham01.png.transform/2col/image.png', thirdPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/serper01.png.transform/2col/image.png', firstPosDriverName: 'VER', secondPosDriverName: 'HAM', thirdPosDriverName: 'PER', raceDone: false, trackImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Great%20Britain%20carbon.png.transform/2col/image.png' },
    { startDate: '02', endDate: '04', month: 'JUL', raceVenue: 'Austria', venueDesc: 'Formula 1 BWT Grosser Preis Von Österreich 2021', venueFlag: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/austria-flag.png.transform/2col/image.png', firstPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/maxver01.png.transform/2col/image.png', secondPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/lewham01.png.transform/2col/image.png', thirdPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/serper01.png.transform/2col/image.png', firstPosDriverName: 'VER', secondPosDriverName: 'HAM', thirdPosDriverName: 'PER', raceDone: false, trackImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Great%20Britain%20carbon.png.transform/2col/image.png' },
    { startDate: '02', endDate: '04', month: 'JUL', raceVenue: 'Austria', venueDesc: 'Formula 1 BWT Grosser Preis Von Österreich 2021', venueFlag: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Flags%2016x9/austria-flag.png.transform/2col/image.png', firstPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/maxver01.png.transform/2col/image.png', secondPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/lewham01.png.transform/2col/image.png', thirdPosImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/drivers/2021/serper01.png.transform/2col/image.png', firstPosDriverName: 'VER', secondPosDriverName: 'HAM', thirdPosDriverName: 'PER', raceDone: false, trackImg: 'https://www.formula1.com/content/dam/fom-website/2018-redesign-assets/Track%20icons%204x3/Great%20Britain%20carbon.png.transform/2col/image.png' }
  ];

  constructor() { }

  ngOnInit(): void {
  }

}
